import type { InfoTipContent } from "@/components/InfoTip";

// Every widget's "what am I looking at" text, in one place.
//
// These are written against the CODE THAT PRODUCES THE NUMBER, not from general
// knowledge about the metric. If a computation changes, its tip changes with it —
// an explanation that has drifted from the thing it explains is worse than none,
// because the user has no way to tell it drifted.
//
// House rules for this file:
//   • name the actual inputs and the actual arithmetic
//   • say which numbers are the device's, which are computed here, and which are
//     a language model's estimate — these are three very different kinds of claim
//   • every caveat states what would make the number wrong or missing

// ── Training ─────────────────────────────────────────────────────────────────

export const TIP_TRAINING_VERDICT: InfoTipContent = {
  what: "The train-today-or-rest call from your most recent AI health analysis, with the reasoning behind it.",
  how: "Generated by Claude (Gemini as fallback) from your training readiness score, acute:chronic load ratio, HRV against your 5-day average, last night's sleep, Body Battery, Garmin training status and your recent sessions. This card reads the analysis that has ALREADY been generated — opening the Training tab never starts a new AI run. When nothing is cached it offers a button instead.",
  caveat: "This is a language model reading your data, not a coaching or medical judgment. The deterministic cards below it are the evidence — where they disagree with the verdict, trust the numbers.",
};

export const TIP_FATIGUE: InfoTipContent = {
  what: "Four overtraining flags computed from your daily training-load series over the last 7 days.",
  how: "Daily load is the sum of Garmin's per-activity training load for that day. ACWR is the Acute:Chronic Workload Ratio — the last 7 days of load (acute, what you just did) divided by your 28-day average week (chronic, what you are conditioned for; the 28-day total ÷ 4). Monotony is Foster's figure: mean daily load ÷ the standard deviation of daily load. Strain is weekly load × monotony. Ramp compares this week's load with the previous week's. All four are computed in code here — the AI never touches them.",
  reads: [
    "ACWR near 1.0 means this week looks like your normal week. 0.8–1.3 is the productive sweet spot; below 0.8 you are detraining; above 1.5 is the load spike associated with injury risk. The premise is that injuries track the SPIKE rather than the absolute volume — a hard week mostly hurts you when it is much harder than the weeks before it.",
    "Monotony above 2.0 means every day looks alike — the pattern that drives overtraining even at modest total volume. Fix it with a genuinely easy day and one genuinely hard one.",
    "A weekly load jump over 50% is flagged on its own, whatever the ratio says.",
  ],
  caveat: "Load comes only from Garmin's per-activity training load. A session the watch didn't record, or recorded without a load value, contributes nothing — so a week of untracked training reads here as an easy week.",
};

export const TIP_LOAD_CHART: InfoTipContent = {
  what: "Your ACWR — Acute:Chronic Workload Ratio, the last 7 days of training load divided by your 28-day average week — over time (top), above the daily load it is computed from (bottom). Both panels share one x-axis.",
  how: "Garmin's own load ratio is plotted on any day the watch reported one. On days it didn't, a rolling 7-day:28-day ratio is computed here from per-activity load and tagged \"computed\" — the route loads 28 extra days of history before the window so the first day already has a real chronic base.",
  reads: [
    "The shaded band is the 0.8–1.3 sweet spot: inside it, you are adding fitness faster than fatigue.",
    "Each bar is that day's total load. No bar means no recorded session that day.",
    "Hover any point to see the date, the ratio, and whether that value came from Garmin or was computed here.",
  ],
  caveat: "A computed ratio and Garmin's own are not quite the same measurement, which is why every value says which it is rather than blending them into one line.",
};

export const TIP_READINESS: InfoTipContent = {
  what: "Garmin's own training readiness score (0–100) for each day in the window.",
  how: "Read straight from that day's cached trainingstatus record — this is the watch's number, reproduced, not re-derived here. Garmin builds it from your sleep, recovery time, HRV status, acute load and recent stress.",
  reads: [
    "Above 70 supports hard training; below 40 says back off. The bands on the chart mark those thresholds.",
  ],
  caveat: "Readiness is only produced by newer Garmin watches, and only for nights you actually wore the device. An empty chart means no score was ever recorded for these dates — not that your readiness was low.",
};

export const TIP_VO2_FITNESS_AGE: InfoTipContent = {
  what: "Garmin's estimated VO2 max — running and cycling tracked as separate values — and the fitness age it derives from them, against your real age.",
  how: "VO2 max: Garmin estimates it from the relationship between your heart rate and your pace (running) or power (cycling) during outdoor sessions. It needs a sustained effort with GPS to recalculate, so it moves in steps rather than continuously. FITNESS AGE: Garmin derives it from four inputs — your chronological age, your VO2 max, your weekly vigorous-intensity minutes, and your body fat percentage (falling back to BMI when no body-composition data exists). Raising VO2 max, training harder more often, or lowering body fat all pull it down.",
  reads: [
    "The VO2 panel is zoomed to the range actually observed, not to zero — a one-point change in VO2 max is a real change and would be invisible on a full-height axis.",
    "Flat stretches are the truth, not a rendering artifact: Garmin only recalculates after a qualifying activity, so the value genuinely holds between them.",
    "On the lower panel, the reference line is your chronological age. Below it means Garmin rates your fitness as younger than your years.",
  ],
  caveat: "Both are device estimates from wrist heart rate, not laboratory measurements. A real VO2 max test or a DEXA body-fat scan would move these numbers, and fitness age inherits every error in the VO2 max it is built on.",
};

export const TIP_WEEKLY_VOLUME: InfoTipContent = {
  what: "Sessions, load, duration, distance and intensity minutes for each Monday-anchored week in the window, against the WHO physical-activity targets.",
  how: "Each week sums the activities recorded within it. Moderate and vigorous minutes are Garmin's own intensity-minute counts, not re-derived from heart rate here. The WHO target is 150 moderate OR 75 vigorous minutes per week, and the bars are drawn against that.",
  reads: [
    "A week tagged PARTIAL is cut off by the edge of the selected window — it is half a week of data, not a bad week of training.",
    "The per-type chips show where the week's sessions actually went.",
  ],
};

export const TIP_ACTIVITIES: InfoTipContent = {
  what: "Every session recorded in the window, newest first, with its full metrics and a CSV export.",
  how: "Garmin names sessions after the device activity profile, so everything on one profile arrives with the same name. ✎ stores a rename locally, keyed to the Garmin activity ID: the cached activity is never rewritten, so a re-sync cannot clobber a rename and clearing one restores the original Garmin name. The field proposes names you have already used for that activity type first.",
  reads: [
    "Chips read: ♥ average heart rate · max heart rate · AE aerobic training effect (0–5) · AnE anaerobic training effect · Load Garmin's training load for that session · ↑ elevation gain.",
    "A \"renamed\" badge means you are looking at your name; hover it to see what Garmin called it.",
  ],
};

// ── Biological age ───────────────────────────────────────────────────────────

// Built from the estimate in hand rather than declared as a constant: the useful
// answer to "why does it say 48?" is the user's OWN measurements that produced
// that number, not a description of the machinery that produced it.
export function bioAgeTip(data: {
  estimate: number;
  delta: number;
  confidence: string;
  keyFactors: string[];
  topImprovement?: string;
}): InfoTipContent {
  const chronological = data.estimate - data.delta;
  const younger = data.delta < 0;

  const verdict = younger
    ? `${Math.abs(data.delta)} year${Math.abs(data.delta) === 1 ? "" : "s"} younger than your actual age of ${chronological}`
    : data.delta === 0
      ? `level with your actual age of ${chronological}`
      : `${data.delta} year${data.delta === 1 ? "" : "s"} older than your actual age of ${chronological}`;

  const confidenceNote: Record<string, string> = {
    high: "Confidence is high — the analysis had a full set of recent measurements to work from.",
    medium: "Confidence is medium — some of the inputs were missing or out of date, so treat the number as approximate.",
    low: "Confidence is low — there was little data to go on. Logging more sleep, HRV and especially blood work would sharpen it considerably.",
  };

  return {
    what: `Your body currently reads as ${data.estimate} — ${verdict}.`,
    how:
      "The estimate is read off your own measurements, weighted by how strongly each one tracks ageing: " +
      "aerobic fitness (VO2 max) and resting heart rate first, then HRV, blood pressure, sleep quality and duration, " +
      "body fat percentage, daily stress and how active you are. Where you have entered blood work it outweighs all of " +
      "those for anything it measures directly — HbA1c, hs-CRP, ApoB, fasting insulin and homocysteine are the strongest " +
      "markers available here. These are the readings that actually moved YOUR number:",
    // One bullet per measurement, so each reading can be read on its own rather
    // than as one long run-on line.
    reads: [
      ...(data.keyFactors.length
        ? data.keyFactors
        : ["No individual readings were cited for this estimate — usually a sign the analysis had thin data to work from that day."]),
      confidenceNote[data.confidence] ?? `Confidence is ${data.confidence}.`,
      ...(data.topImprovement
        ? [`Biggest lever from here: ${data.topImprovement}`]
        : []),
    ],
    caveat:
      "This is an informed reading of your metrics, not a clinical or epigenetic measurement of ageing. " +
      "It can shift a year either way between analyses without anything about you having changed — watch where it " +
      "travels over months, not what it says today.",
  };
}

export const TIP_BIO_AGE_CHART: InfoTipContent = {
  what: "Every biological-age estimate made so far, plotted against your real age, so you can see which way it is heading.",
  how: "One point per day that a health analysis ran — each estimate is read off that day's fitness, heart-rate, sleep, body-composition and blood-work figures. Open the Biological Age card on this page to see which measurements produced the latest one.",
  reads: [
    "The direction and slope are the signal. A line drifting down means the measurements behind it are improving faster than you are ageing.",
    "Gaps in the line are days no analysis ran, not days without data.",
  ],
  caveat: "Each point is estimated independently, so a single day's jump of a year or two is noise rather than real physiological change. Read it across weeks.",
};

// ── Recovery & correlations ──────────────────────────────────────────────────

export const TIP_CORRELATIONS: InfoTipContent = {
  what: "What each supplement, behavior and kind of training session does to the FOLLOWING day's recovery, over the last 30 days.",
  how: "For every factor, the days you had it are compared against the days you didn't, on the next day's sleep score, deep sleep, sleep duration, HRV, stress, resting heart rate and Body Battery recharge. A factor needs at least 4 days in each group before it is shown at all. The next day is the right comparison because a date's sleep and HRV describe the night that ended that morning. Every number here is computed in code — the AI writes the narrative around them but never the figures themselves.",
  reads: [
    "Green means the difference runs in the beneficial direction for that metric — which for resting heart rate and stress means a lower number.",
    "Hover any chip to see the two averages it was computed from, and how many days went into each.",
  ],
  caveat: "This is correlation over a short window, not causation. Habits cluster — hard training days are also late-eating days — so treat a strong chip as a hypothesis worth testing deliberately, which is what the suggested self-experiments are for.",
};

export const TIP_SLEEP_TREND: InfoTipContent = {
  what: "Your Garmin sleep score (top) over the hours you actually slept (bottom), sharing one x-axis.",
  how: "Read from the cached sleep record for each date — this route never calls Garmin, so changing the window is instant. Garmin scores a night from its duration, the stage mix (deep/REM/light), how much you were awake, and overnight HRV and respiration.",
  reads: [
    "Reference lines mark 60 and 80 on the score, which are Garmin's fair/good/excellent boundaries, and 8 hours on the duration bars.",
    "A missing day is a night with no recorded sleep — the watch was off, or off your wrist.",
  ],
};

export const TIP_BODY_BATTERY: InfoTipContent = {
  what: "The range each day ran between — the band spans that day's lowest and highest Body Battery.",
  how: "Read from each date's cached Body Battery record. Garmin builds the 0–100 figure from HRV, stress and activity, charging it during rest and sleep and draining it with activity and stress.",
  reads: [
    "A band that starts high and ends low is a heavy day; a band that never gets high is a recovery debt building up across days.",
  ],
};

export const TIP_STRESS: InfoTipContent = {
  what: "Your daily average Garmin stress score across the window.",
  how: "Garmin derives stress (1–100) from heart-rate variability while you are not moving — it cannot measure stress during activity, so exercise time is excluded rather than counted as stress.",
  reads: [
    "0–25 rest · 26–50 low · 51–75 medium · 76–100 high.",
  ],
};

export const TIP_BLOOD_PRESSURE: InfoTipContent = {
  what: "Systolic and diastolic readings over time, with the latest reading's ACC/AHA category.",
  how: "Read from cached blood-pressure records — readings taken on a Garmin Index BPM or entered by hand in Garmin Connect. Days without a reading are omitted from the line rather than interpolated, because blood pressure is measured sparsely and a drawn-through line would invent readings you never took.",
  reads: [
    "ACC/AHA categories: normal under 120/80 · elevated 120–129 systolic · stage 1 130–139 or 80–89 · stage 2 at or above 140/90.",
  ],
  caveat: "A single reading is not a diagnosis — cuff readings vary with posture, time of day and caffeine. Clinical categories are meant to be applied to an average of repeated readings.",
};

// ── Overview & nutrition ─────────────────────────────────────────────────────

export const TIP_RESILIENCE: InfoTipContent = {
  what: "How well your body is absorbing stress right now, measured against your own recent normal rather than against anyone else's.",
  how: "Four signals are compared over the last 7 days against your own 28-day baseline: HRV, resting heart rate, average daily stress, and overnight Body Battery recharge. Each is scored around 50, where 50 means \"exactly at your baseline\" — roughly ±10% off baseline moves a component ±30 points. The headline score is the weighted average of whichever components had enough data. All of it is computed in code; no AI and no population norms are involved.",
  reads: [
    "50 is your own normal, not a pass mark. Above it you are handling load better than usual lately; below it you are handling it worse.",
    "The component chips show which signal is driving the score, and by how much it has moved off baseline.",
    "Because the baseline is yours, the score says nothing about how you compare to anyone else — only about which direction you are moving.",
  ],
  caveat: "A component needs enough days in both the recent window and the baseline before it counts. Early on, or after a gap in wearing the watch, the score rests on fewer signals than it looks like.",
};

export const TIP_METRIC_COMPARE: InfoTipContent = {
  what: "Any two of your daily metrics drawn one above the other on a shared timeline, so you can eyeball whether they move together.",
  how: "Both panels read the same cached per-day rows the rest of the app uses — sleep, HRV, resting heart rate, steps, stress, Body Battery, calories and protein. They are deliberately drawn as two stacked panels rather than two lines on one dual axis: a dual axis lets you manufacture any correlation you like by rescaling one side, and the shape you see here is the shape in the data.",
  reads: [
    "Line up peaks and troughs by date. Remember that sleep and HRV for a date describe the night that ENDED that morning, so a behavior's effect usually shows on the following day's point.",
  ],
  caveat: "Two lines moving together is a prompt to look closer, not evidence of a link. The Correlations card does the same comparison with actual arithmetic and a minimum sample size.",
};

export const TIP_WEIGHT: InfoTipContent = {
  what: "Your logged body weight over time, with any body-composition readings recorded alongside it.",
  how: "Plotted from what you have entered plus anything a connected Garmin scale reported. Nothing here is estimated or smoothed — every point is a reading you or the scale recorded on that date.",
  reads: [
    "Day-to-day swings of a kilogram or more are mostly water, food in transit, and glycogen. The trend across weeks is the part that reflects actual tissue change.",
    "Weighing under the same conditions each time — same time of day, before eating — makes the trend readable far sooner.",
  ],
};

export const TIP_JOURNAL: InfoTipContent = {
  what: "One-tap tags for the things that affect recovery but no wearable can see — alcohol, late caffeine, a late meal, sauna, poor sleep environment, travel, illness.",
  how: "Each tag is stored against the day you tap it. Nothing happens immediately; the value comes later, when the Correlations card compares your tagged days against your untagged ones on the FOLLOWING day's sleep, HRV, stress and recovery.",
  reads: [
    "A factor needs at least 4 tagged days and 4 untagged days before any comparison will appear, so tagging honestly and consistently for a few weeks is what makes this pay off.",
    "Tag what actually happened, including the days you would rather not record — a journal with only the good days in it makes every comparison look flattering and tells you nothing.",
  ],
};

export const TIP_MICROS: InfoTipContent = {
  what: "How much of each tracked vitamin and mineral you got today, stacked from food and from the supplements you actually checked off.",
  how: "Food micronutrients come from the AI's per-food estimate when a meal is logged. Supplement contributions are matched by name against a nutrient catalog and converted into the same unit as the target — including IU to micrograms for vitamin D. Only supplements you have ticked as taken today are counted, so the bar reflects what you actually swallowed rather than what is in your stack.",
  reads: [
    "The target line is the adult reference intake; the upper limit, where one exists, is the point past which more is a risk rather than a benefit.",
    "The food and supplement portions are stacked separately so you can see which is carrying a nutrient — and whether a supplement is topping up a gap or duplicating something your diet already covers.",
  ],
  caveat: "Food micronutrients are AI estimates from a description or a photo, and are much rougher than the calorie and macro figures. Read them as \"roughly covered\" versus \"clearly short\", not as precise intakes. A blend whose label you haven't recorded contributes nothing here.",
};

export const TIP_LABS: InfoTipContent = {
  what: "Your blood panels — the only measurements in this app taken from inside the body rather than inferred from the wrist.",
  how: "Each value is stored exactly as your lab printed it, in the unit the lab used, and converted only for comparison — mg/dL and mmol/L differ by country and normalising on the way in would destroy the original reading. Each marker is checked against two ranges: the reference range (outside it is a flag) and a tighter optimal range (inside reference but outside optimal is an improvement target, not a problem).",
  reads: [
    "Out-of-range and sub-optimal markers are listed first, each with a status dot and the change since your previous panel.",
    "The draw date travels with every value, so an old panel is read as a starting point rather than as current status.",
    "These values outrank every wearable estimate for anything they measure directly, and they carry the most weight in the biological-age estimate.",
  ],
  caveat: "A single panel is a snapshot taken under one set of conditions — fasting, hydration, recent training and time of day all move these numbers. Interpretation belongs with your doctor, not with this app.",
};
